const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Json,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.urlencode
	];
};
self.C3_JsPropNameTable = [
	{М1фон: 0},
	{М1КНачать: 0},
	{М2Фон: 0},
	{М2КЯИмениннциа: 0},
	{М2КИграюВпервые: 0},
	{М2КИграюПовторно: 0},
	{М2КДоскаПобедителей: 0},
	{М3Фон: 0},
	{М3КПродолжить: 0},
	{ВводТекста: 0},
	{М4Фон: 0},
	{М4КПродолжить: 0},
	{М5Фон: 0},
	{М5КДомой: 0},
	{М5КВправо: 0},
	{М6Фон: 0},
	{М6КДомой: 0},
	{М6КВправо: 0},
	{М6кНазад: 0},
	{М7Фон: 0},
	{М7КДомой: 0},
	{М7кНазад: 0},
	{М7КВправо: 0},
	{М8Фон: 0},
	{М8КДомой: 0},
	{М8кНазад: 0},
	{М5ИмяМесто1: 0},
	{М5ИмяМесто2: 0},
	{М5ИмяМесто3: 0},
	{М5ИмяМесто4: 0},
	{М5ИмяМесто5: 0},
	{М5ИмяМесто6: 0},
	{М5ИмяМесто7: 0},
	{М5ИмяМесто8: 0},
	{М5ИмяМесто9: 0},
	{М5ИмяМесто10: 0},
	{М5БаллыМесто1: 0},
	{М5БаллыМесто2: 0},
	{М5БаллыМесто3: 0},
	{М5БаллыМесто4: 0},
	{М5БаллыМесто5: 0},
	{М5БаллыМесто6: 0},
	{М5БаллыМесто7: 0},
	{М5БаллыМесто8: 0},
	{М5БаллыМесто9: 0},
	{М5БаллыМесто10: 0},
	{М5КПожеланияМесто1: 0},
	{М5КПожеланияМесто2: 0},
	{М5КПожеланияМесто3: 0},
	{М5КПожеланияМесто4: 0},
	{М5КПожеланияМесто5: 0},
	{М5КПожеланияМесто6: 0},
	{М5КПожеланияМесто7: 0},
	{М5КПожеланияМесто8: 0},
	{М5КПожеланияМесто9: 0},
	{М5КПожеланияМесто10: 0},
	{М6ИмяМесто11: 0},
	{М6ИмяМесто12: 0},
	{М6ИмяМесто13: 0},
	{М6ИмяМесто14: 0},
	{М6ИмяМесто15: 0},
	{М6ИмяМесто16: 0},
	{М6ИмяМесто17: 0},
	{М6ИмяМесто18: 0},
	{М6ИмяМесто19: 0},
	{М6ИмяМесто20: 0},
	{М6БаллыМесто11: 0},
	{М6БаллыМесто12: 0},
	{М6БаллыМесто13: 0},
	{М6БаллыМесто14: 0},
	{М6БаллыМесто15: 0},
	{М6БаллыМесто16: 0},
	{М6БаллыМесто17: 0},
	{М6БаллыМесто18: 0},
	{М6БаллыМесто19: 0},
	{М6БаллыМесто20: 0},
	{М6КПожеланияМесто11: 0},
	{М6КПожеланияМесто12: 0},
	{М6КПожеланияМесто13: 0},
	{М6КПожеланияМесто14: 0},
	{М6КПожеланияМесто15: 0},
	{М6КПожеланияМесто16: 0},
	{М6КПожеланияМесто17: 0},
	{М6КПожеланияМесто18: 0},
	{М6КПожеланияМесто19: 0},
	{М6КПожеланияМесто20: 0},
	{М7ИмяМесто21: 0},
	{М7ИмяМесто22: 0},
	{М7ИмяМесто23: 0},
	{М7ИмяМесто24: 0},
	{М7ИмяМесто25: 0},
	{М7ИмяМесто26: 0},
	{М7ИмяМесто27: 0},
	{М7ИмяМесто28: 0},
	{М7ИмяМесто29: 0},
	{М7ИмяМесто30: 0},
	{М7БаллыМесто21: 0},
	{М7БаллыМесто22: 0},
	{М7БаллыМесто23: 0},
	{М7БаллыМесто24: 0},
	{М7БаллыМесто25: 0},
	{М7БаллыМесто26: 0},
	{М7БаллыМесто27: 0},
	{М7БаллыМесто28: 0},
	{М7БаллыМесто29: 0},
	{М7БаллыМесто30: 0},
	{М7КПожеланияМесто21: 0},
	{М7КПожеланияМесто22: 0},
	{М7КПожеланияМесто23: 0},
	{М7КПожеланияМесто24: 0},
	{М7КПожеланияМесто25: 0},
	{М7КПожеланияМесто26: 0},
	{М7КПожеланияМесто27: 0},
	{М7КПожеланияМесто28: 0},
	{М7КПожеланияМесто29: 0},
	{М7КПожеланияМесто30: 0},
	{М8ИмяМесто31: 0},
	{М8ИмяМесто32: 0},
	{М8ИмяМесто33: 0},
	{М8ИмяМесто34: 0},
	{М8ИмяМесто35: 0},
	{М8ИмяМесто36: 0},
	{М8ИмяМесто37: 0},
	{М8ИмяМесто38: 0},
	{М8ИмяМесто39: 0},
	{М8ИмяМесто40: 0},
	{М8БаллыМесто31: 0},
	{М8БаллыМесто32: 0},
	{М8БаллыМесто33: 0},
	{М8БаллыМесто34: 0},
	{М8БаллыМесто35: 0},
	{М8БаллыМесто36: 0},
	{М8БаллыМесто37: 0},
	{М8БаллыМесто38: 0},
	{М8БаллыМесто39: 0},
	{М8БаллыМесто40: 0},
	{М8КПожеланияМесто31: 0},
	{М8КПожеланияМесто32: 0},
	{М8КПожеланияМесто33: 0},
	{М8КПожеланияМесто34: 0},
	{М8КПожеланияМесто35: 0},
	{М8КПожеланияМесто36: 0},
	{М8КПожеланияМесто37: 0},
	{М8КПожеланияМесто38: 0},
	{М8КПожеланияМесто39: 0},
	{М8КПожеланияМесто40: 0},
	{М9фон: 0},
	{М9КДалее1: 0},
	{М9Фон2: 0},
	{М9КДалее2: 0},
	{М9Фон3: 0},
	{М9кНаПомощь: 0},
	{М10Фон: 0},
	{М10кГотово: 0},
	{М10ВводТекстаПервоеВпечатление: 0},
	{М11Фон: 0},
	{М11КПлюсикДети: 0},
	{М11КПлюсикМуж: 0},
	{М11КПлюсикРабота: 0},
	{М11Готово: 0},
	{М11Фон2: 0},
	{М11ККрестикДети: 0},
	{М11КДваСына: 0},
	{М11КДвеДочери: 0},
	{М11КСынИДочь: 0},
	{М11Фон3: 0},
	{М11ККрестикМуж: 0},
	{М11КДиспетчер: 0},
	{М11КЭлектровоз: 0},
	{М11КТепловоза: 0},
	{М11КИнженерМуж: 0},
	{М11Фон4: 0},
	{М11ККрестикПрофессия: 0},
	{М11КЭкономист: 0},
	{М11КГлавныйБухгалетр: 0},
	{М11КИнженерПоТруду: 0},
	{М12Фон: 0},
	{М11ТДвоеДетей: 0},
	{М11ТМашинистТепловоза: 0},
	{М11ТИнженерПоТруду: 0},
	{М11КДалее: 0},
	{М13Фон: 0},
	{Перетаскивание: 0},
	{М13КНиночка: 0},
	{М13КЛапочка: 0},
	{М13кЛюлёк: 0},
	{М13ККрасотка: 0},
	{М14Фон: 0},
	{М14КБилеты: 0},
	{М14ККопирка: 0},
	{М14КДоговаривалась: 0},
	{М14Антивирус: 0},
	{М15Фон: 0},
	{М15Антивирус: 0},
	{Твинанимация: 0},
	{М15ТекстИры1: 0},
	{М15ТекстИры2: 0},
	{М15ТекстИры3: 0},
	{М15ТекстКопирки1: 0},
	{М15ТекстКопирки2: 0},
	{М15ТекстКопирки3: 0},
	{М15Фон2: 0},
	{М14Антивирус2: 0},
	{М15КДалее: 0},
	{М16Фон: 0},
	{М16Антивирус: 0},
	{М16КСумкаИры: 0},
	{М16КСумкаНины: 0},
	{М16Фон2: 0},
	{М16Антивирус2: 0},
	{М16КДалее: 0},
	{М17Фон: 0},
	{М17Антивирус: 0},
	{М17ККурган: 0},
	{М17КНовосибирск: 0},
	{М17Фон2: 0},
	{М17Антивирус2: 0},
	{М17КОченьЖаль: 0},
	{М17Фон3: 0},
	{М17КГорько: 0},
	{М17Антивирус3: 0},
	{М18Фон: 0},
	{М18Анивирус: 0},
	{М18КДальше: 0},
	{М19Фон: 0},
	{М19Анивирус: 0},
	{М19Помидор: 0},
	{М19Лук: 0},
	{М19Нож: 0},
	{М11ТИнженерПоТруду2: 0},
	{М19КДальше: 0},
	{М120Фон: 0},
	{М20Анивирус: 0},
	{М20КДальше: 0},
	{М20ТТекстЛук: 0},
	{М20Помидор: 0},
	{М20Лук: 0},
	{М20Нож: 0},
	{М21Фон: 0},
	{М20Анивирус2: 0},
	{М21Масло: 0},
	{М21Пепси: 0},
	{М21Вода: 0},
	{М21Соус: 0},
	{М21Лимонад: 0},
	{М22Фон: 0},
	{М22Антивирус: 0},
	{М22Сумочка: 0},
	{М22Розы: 0},
	{М22Кулаки: 0},
	{М22Зонтик: 0},
	{М22Фон2: 0},
	{М22Антивирус2: 0},
	{М22КДалееСумка: 0},
	{М22Фон3: 0},
	{М22Антивирус3: 0},
	{М22КДалееКулаки: 0},
	{М22Фон4: 0},
	{М22Антивирус4: 0},
	{М22КДалееЗонтик: 0},
	{М22Фон5: 0},
	{М22Антивирус5: 0},
	{М22КДалееИстория: 0},
	{М23Фон: 0},
	{М23Антивирус: 0},
	{М23КПамятник: 0},
	{М23КАльбом: 0},
	{М23КФотозона: 0},
	{М23Фон2: 0},
	{М23НинаДвижуха: 0},
	{М23КПамятник2: 0},
	{М23Антивирус2: 0},
	{М24Фон: 0},
	{М24КПриступить: 0},
	{М25Фон: 0},
	{М25КСтарт: 0},
	{М25ПризракПазл1: 0},
	{М25ПризракПазл2: 0},
	{М25ПризракПазл3: 0},
	{М25ПризракПазл4: 0},
	{М25ПризракПазл5: 0},
	{М25ПризракПазл6: 0},
	{М25Пазл1: 0},
	{М25Пазл2: 0},
	{М25Пазл3: 0},
	{М25Пазл4: 0},
	{М25Пазл5: 0},
	{М25Пазл6: 0},
	{М26Фон: 0},
	{М26ВводТекстаПожелание: 0},
	{М26КОтправить: 0},
	{М27Фон: 0},
	{М27КДоскаПобедителей: 0},
	{Мышь: 0},
	{Тач: 0},
	{М11Проверка: 0},
	{М13ПолеВнесения: 0},
	{М13КДалее: 0},
	{М15КДалееКопирка: 0},
	{М19Доска: 0},
	{М20Доска: 0},
	{М21Миска: 0},
	{М21КДалее: 0},
	{М21Фон2: 0},
	{М20Анивирус3: 0},
	{М21КДалее2: 0},
	{М20ТТекстЛук2: 0},
	{М21Пепси2: 0},
	{М17Фон4: 0},
	{М17КДальше: 0},
	{М17Антивирус4: 0},
	{М23КДалее: 0},
	{М25ТСекунды: 0},
	{М25КДалее: 0},
	{М25проверка: 0},
	{М5Фон2: 0},
	{М5ПервоеВпечатление: 0},
	{М5Пожелание: 0},
	{М5КЗакрыть: 0},
	{М6Фон2: 0},
	{М6ПервоеВпечатление: 0},
	{М6Пожелание: 0},
	{М6КЗакрыть: 0},
	{М7Фон2: 0},
	{М7ПервоеВпечатление: 0},
	{М7Пожелание: 0},
	{М7КЗакрыть: 0},
	{М8Фон2: 0},
	{М8ПервоеВпечатление: 0},
	{М8КЗакрыть: 0},
	{М8Пожелание: 0},
	{М13Проверка: 0},
	{М15Проверка: 0},
	{М16Проверка: 0},
	{М17Проверка: 0},
	{М21Проверка: 0},
	{М22Проверка: 0},
	{М23Проверка: 0},
	{AJAX: 0},
	{ВводТекста2: 0},
	{М27Проверка: 0},
	{М27ТЗагрузка: 0},
	{М5МассивИмена: 0},
	{М5МассивБаллы: 0},
	{М5МассивВпечатления: 0},
	{М5МассивПожелания: 0},
	{JSON: 0},
	{М27ТЗагрузка2: 0},
	{М26Баллы: 0},
	{М3ИмяИгрока: 0},
	{ЗарабатываемБаллы: 0},
	{М10ПервоеВпечатление: 0},
	{М11ДетиОтветДан: 0},
	{М11ОтветДанМуж: 0},
	{М11ОтветДанКемРаботала: 0},
	{М11Баллы: 0},
	{М15ВремяПроявления: 0},
	{М19ПомидорПорезан: 0},
	{М25ИграОкончена: 0},
	{М25ИграИдетПазлы: 0},
	{М25БаллыПазла: 0},
	{М25Секунды: 0},
	{м25баллызасчитаны: 0},
	{М25ПазлыНаМестах: 0},
	{М26Пожелания: 0}
];

self.InstanceType = {
	М1фон: class extends self.ISpriteInstance {},
	М1КНачать: class extends self.ISpriteInstance {},
	М2Фон: class extends self.ISpriteInstance {},
	М2КЯИмениннциа: class extends self.ISpriteInstance {},
	М2КИграюВпервые: class extends self.ISpriteInstance {},
	М2КИграюПовторно: class extends self.ISpriteInstance {},
	М2КДоскаПобедителей: class extends self.ISpriteInstance {},
	М3Фон: class extends self.ISpriteInstance {},
	М3КПродолжить: class extends self.ISpriteInstance {},
	ВводТекста: class extends self.ITextInputInstance {},
	М4Фон: class extends self.ISpriteInstance {},
	М4КПродолжить: class extends self.ISpriteInstance {},
	М5Фон: class extends self.ISpriteInstance {},
	М5КДомой: class extends self.ISpriteInstance {},
	М5КВправо: class extends self.ISpriteInstance {},
	М6Фон: class extends self.ISpriteInstance {},
	М6КДомой: class extends self.ISpriteInstance {},
	М6КВправо: class extends self.ISpriteInstance {},
	М6кНазад: class extends self.ISpriteInstance {},
	М7Фон: class extends self.ISpriteInstance {},
	М7КДомой: class extends self.ISpriteInstance {},
	М7кНазад: class extends self.ISpriteInstance {},
	М7КВправо: class extends self.ISpriteInstance {},
	М8Фон: class extends self.ISpriteInstance {},
	М8КДомой: class extends self.ISpriteInstance {},
	М8кНазад: class extends self.ISpriteInstance {},
	М5ИмяМесто1: class extends self.ITextInstance {},
	М5ИмяМесто2: class extends self.ITextInstance {},
	М5ИмяМесто3: class extends self.ITextInstance {},
	М5ИмяМесто4: class extends self.ITextInstance {},
	М5ИмяМесто5: class extends self.ITextInstance {},
	М5ИмяМесто6: class extends self.ITextInstance {},
	М5ИмяМесто7: class extends self.ITextInstance {},
	М5ИмяМесто8: class extends self.ITextInstance {},
	М5ИмяМесто9: class extends self.ITextInstance {},
	М5ИмяМесто10: class extends self.ITextInstance {},
	М5БаллыМесто1: class extends self.ITextInstance {},
	М5БаллыМесто2: class extends self.ITextInstance {},
	М5БаллыМесто3: class extends self.ITextInstance {},
	М5БаллыМесто4: class extends self.ITextInstance {},
	М5БаллыМесто5: class extends self.ITextInstance {},
	М5БаллыМесто6: class extends self.ITextInstance {},
	М5БаллыМесто7: class extends self.ITextInstance {},
	М5БаллыМесто8: class extends self.ITextInstance {},
	М5БаллыМесто9: class extends self.ITextInstance {},
	М5БаллыМесто10: class extends self.ITextInstance {},
	М5КПожеланияМесто1: class extends self.ISpriteInstance {},
	М5КПожеланияМесто2: class extends self.ISpriteInstance {},
	М5КПожеланияМесто3: class extends self.ISpriteInstance {},
	М5КПожеланияМесто4: class extends self.ISpriteInstance {},
	М5КПожеланияМесто5: class extends self.ISpriteInstance {},
	М5КПожеланияМесто6: class extends self.ISpriteInstance {},
	М5КПожеланияМесто7: class extends self.ISpriteInstance {},
	М5КПожеланияМесто8: class extends self.ISpriteInstance {},
	М5КПожеланияМесто9: class extends self.ISpriteInstance {},
	М5КПожеланияМесто10: class extends self.ISpriteInstance {},
	М6ИмяМесто11: class extends self.ITextInstance {},
	М6ИмяМесто12: class extends self.ITextInstance {},
	М6ИмяМесто13: class extends self.ITextInstance {},
	М6ИмяМесто14: class extends self.ITextInstance {},
	М6ИмяМесто15: class extends self.ITextInstance {},
	М6ИмяМесто16: class extends self.ITextInstance {},
	М6ИмяМесто17: class extends self.ITextInstance {},
	М6ИмяМесто18: class extends self.ITextInstance {},
	М6ИмяМесто19: class extends self.ITextInstance {},
	М6ИмяМесто20: class extends self.ITextInstance {},
	М6БаллыМесто11: class extends self.ITextInstance {},
	М6БаллыМесто12: class extends self.ITextInstance {},
	М6БаллыМесто13: class extends self.ITextInstance {},
	М6БаллыМесто14: class extends self.ITextInstance {},
	М6БаллыМесто15: class extends self.ITextInstance {},
	М6БаллыМесто16: class extends self.ITextInstance {},
	М6БаллыМесто17: class extends self.ITextInstance {},
	М6БаллыМесто18: class extends self.ITextInstance {},
	М6БаллыМесто19: class extends self.ITextInstance {},
	М6БаллыМесто20: class extends self.ITextInstance {},
	М6КПожеланияМесто11: class extends self.ISpriteInstance {},
	М6КПожеланияМесто12: class extends self.ISpriteInstance {},
	М6КПожеланияМесто13: class extends self.ISpriteInstance {},
	М6КПожеланияМесто14: class extends self.ISpriteInstance {},
	М6КПожеланияМесто15: class extends self.ISpriteInstance {},
	М6КПожеланияМесто16: class extends self.ISpriteInstance {},
	М6КПожеланияМесто17: class extends self.ISpriteInstance {},
	М6КПожеланияМесто18: class extends self.ISpriteInstance {},
	М6КПожеланияМесто19: class extends self.ISpriteInstance {},
	М6КПожеланияМесто20: class extends self.ISpriteInstance {},
	М7ИмяМесто21: class extends self.ITextInstance {},
	М7ИмяМесто22: class extends self.ITextInstance {},
	М7ИмяМесто23: class extends self.ITextInstance {},
	М7ИмяМесто24: class extends self.ITextInstance {},
	М7ИмяМесто25: class extends self.ITextInstance {},
	М7ИмяМесто26: class extends self.ITextInstance {},
	М7ИмяМесто27: class extends self.ITextInstance {},
	М7ИмяМесто28: class extends self.ITextInstance {},
	М7ИмяМесто29: class extends self.ITextInstance {},
	М7ИмяМесто30: class extends self.ITextInstance {},
	М7БаллыМесто21: class extends self.ITextInstance {},
	М7БаллыМесто22: class extends self.ITextInstance {},
	М7БаллыМесто23: class extends self.ITextInstance {},
	М7БаллыМесто24: class extends self.ITextInstance {},
	М7БаллыМесто25: class extends self.ITextInstance {},
	М7БаллыМесто26: class extends self.ITextInstance {},
	М7БаллыМесто27: class extends self.ITextInstance {},
	М7БаллыМесто28: class extends self.ITextInstance {},
	М7БаллыМесто29: class extends self.ITextInstance {},
	М7БаллыМесто30: class extends self.ITextInstance {},
	М7КПожеланияМесто21: class extends self.ISpriteInstance {},
	М7КПожеланияМесто22: class extends self.ISpriteInstance {},
	М7КПожеланияМесто23: class extends self.ISpriteInstance {},
	М7КПожеланияМесто24: class extends self.ISpriteInstance {},
	М7КПожеланияМесто25: class extends self.ISpriteInstance {},
	М7КПожеланияМесто26: class extends self.ISpriteInstance {},
	М7КПожеланияМесто27: class extends self.ISpriteInstance {},
	М7КПожеланияМесто28: class extends self.ISpriteInstance {},
	М7КПожеланияМесто29: class extends self.ISpriteInstance {},
	М7КПожеланияМесто30: class extends self.ISpriteInstance {},
	М8ИмяМесто31: class extends self.ITextInstance {},
	М8ИмяМесто32: class extends self.ITextInstance {},
	М8ИмяМесто33: class extends self.ITextInstance {},
	М8ИмяМесто34: class extends self.ITextInstance {},
	М8ИмяМесто35: class extends self.ITextInstance {},
	М8ИмяМесто36: class extends self.ITextInstance {},
	М8ИмяМесто37: class extends self.ITextInstance {},
	М8ИмяМесто38: class extends self.ITextInstance {},
	М8ИмяМесто39: class extends self.ITextInstance {},
	М8ИмяМесто40: class extends self.ITextInstance {},
	М8БаллыМесто31: class extends self.ITextInstance {},
	М8БаллыМесто32: class extends self.ITextInstance {},
	М8БаллыМесто33: class extends self.ITextInstance {},
	М8БаллыМесто34: class extends self.ITextInstance {},
	М8БаллыМесто35: class extends self.ITextInstance {},
	М8БаллыМесто36: class extends self.ITextInstance {},
	М8БаллыМесто37: class extends self.ITextInstance {},
	М8БаллыМесто38: class extends self.ITextInstance {},
	М8БаллыМесто39: class extends self.ITextInstance {},
	М8БаллыМесто40: class extends self.ITextInstance {},
	М8КПожеланияМесто31: class extends self.ISpriteInstance {},
	М8КПожеланияМесто32: class extends self.ISpriteInstance {},
	М8КПожеланияМесто33: class extends self.ISpriteInstance {},
	М8КПожеланияМесто34: class extends self.ISpriteInstance {},
	М8КПожеланияМесто35: class extends self.ISpriteInstance {},
	М8КПожеланияМесто36: class extends self.ISpriteInstance {},
	М8КПожеланияМесто37: class extends self.ISpriteInstance {},
	М8КПожеланияМесто38: class extends self.ISpriteInstance {},
	М8КПожеланияМесто39: class extends self.ISpriteInstance {},
	М8КПожеланияМесто40: class extends self.ISpriteInstance {},
	М9фон: class extends self.ISpriteInstance {},
	М9КДалее1: class extends self.ISpriteInstance {},
	М9Фон2: class extends self.ISpriteInstance {},
	М9КДалее2: class extends self.ISpriteInstance {},
	М9Фон3: class extends self.ISpriteInstance {},
	М9кНаПомощь: class extends self.ISpriteInstance {},
	М10Фон: class extends self.ISpriteInstance {},
	М10кГотово: class extends self.ISpriteInstance {},
	М10ВводТекстаПервоеВпечатление: class extends self.ITextInputInstance {},
	М11Фон: class extends self.ISpriteInstance {},
	М11КПлюсикДети: class extends self.ISpriteInstance {},
	М11КПлюсикМуж: class extends self.ISpriteInstance {},
	М11КПлюсикРабота: class extends self.ISpriteInstance {},
	М11Готово: class extends self.ISpriteInstance {},
	М11Фон2: class extends self.ISpriteInstance {},
	М11ККрестикДети: class extends self.ISpriteInstance {},
	М11КДваСына: class extends self.ISpriteInstance {},
	М11КДвеДочери: class extends self.ISpriteInstance {},
	М11КСынИДочь: class extends self.ISpriteInstance {},
	М11Фон3: class extends self.ISpriteInstance {},
	М11ККрестикМуж: class extends self.ISpriteInstance {},
	М11КДиспетчер: class extends self.ISpriteInstance {},
	М11КЭлектровоз: class extends self.ISpriteInstance {},
	М11КТепловоза: class extends self.ISpriteInstance {},
	М11КИнженерМуж: class extends self.ISpriteInstance {},
	М11Фон4: class extends self.ISpriteInstance {},
	М11ККрестикПрофессия: class extends self.ISpriteInstance {},
	М11КЭкономист: class extends self.ISpriteInstance {},
	М11КГлавныйБухгалетр: class extends self.ISpriteInstance {},
	М11КИнженерПоТруду: class extends self.ISpriteInstance {},
	М12Фон: class extends self.ISpriteInstance {},
	М11ТДвоеДетей: class extends self.ITextInstance {},
	М11ТМашинистТепловоза: class extends self.ITextInstance {},
	М11ТИнженерПоТруду: class extends self.ITextInstance {},
	М11КДалее: class extends self.ISpriteInstance {},
	М13Фон: class extends self.ISpriteInstance {},
	М13КНиночка: class extends self.ISpriteInstance {},
	М13КЛапочка: class extends self.ISpriteInstance {},
	М13кЛюлёк: class extends self.ISpriteInstance {},
	М13ККрасотка: class extends self.ISpriteInstance {},
	М14Фон: class extends self.ISpriteInstance {},
	М14КБилеты: class extends self.ISpriteInstance {},
	М14ККопирка: class extends self.ISpriteInstance {},
	М14КДоговаривалась: class extends self.ISpriteInstance {},
	М14Антивирус: class extends self.ISpriteInstance {},
	М15Фон: class extends self.ISpriteInstance {},
	М15Антивирус: class extends self.ISpriteInstance {},
	М15ТекстИры1: class extends self.ITextInstance {},
	М15ТекстИры2: class extends self.ITextInstance {},
	М15ТекстИры3: class extends self.ITextInstance {},
	М15ТекстКопирки1: class extends self.ITextInstance {},
	М15ТекстКопирки2: class extends self.ITextInstance {},
	М15ТекстКопирки3: class extends self.ITextInstance {},
	М15Фон2: class extends self.ISpriteInstance {},
	М14Антивирус2: class extends self.ISpriteInstance {},
	М15КДалее: class extends self.ISpriteInstance {},
	М16Фон: class extends self.ISpriteInstance {},
	М16Антивирус: class extends self.ISpriteInstance {},
	М16КСумкаИры: class extends self.ISpriteInstance {},
	М16КСумкаНины: class extends self.ISpriteInstance {},
	М16Фон2: class extends self.ISpriteInstance {},
	М16Антивирус2: class extends self.ISpriteInstance {},
	М16КДалее: class extends self.ISpriteInstance {},
	М17Фон: class extends self.ISpriteInstance {},
	М17Антивирус: class extends self.ISpriteInstance {},
	М17ККурган: class extends self.ISpriteInstance {},
	М17КНовосибирск: class extends self.ISpriteInstance {},
	М17Фон2: class extends self.ISpriteInstance {},
	М17Антивирус2: class extends self.ISpriteInstance {},
	М17КОченьЖаль: class extends self.ISpriteInstance {},
	М17Фон3: class extends self.ISpriteInstance {},
	М17КГорько: class extends self.ISpriteInstance {},
	М17Антивирус3: class extends self.ISpriteInstance {},
	М18Фон: class extends self.ISpriteInstance {},
	М18Анивирус: class extends self.ISpriteInstance {},
	М18КДальше: class extends self.ISpriteInstance {},
	М19Фон: class extends self.ISpriteInstance {},
	М19Анивирус: class extends self.ISpriteInstance {},
	М19Помидор: class extends self.ISpriteInstance {},
	М19Лук: class extends self.ISpriteInstance {},
	М19Нож: class extends self.ISpriteInstance {},
	М11ТИнженерПоТруду2: class extends self.ITextInstance {},
	М19КДальше: class extends self.ISpriteInstance {},
	М120Фон: class extends self.ISpriteInstance {},
	М20Анивирус: class extends self.ISpriteInstance {},
	М20КДальше: class extends self.ISpriteInstance {},
	М20ТТекстЛук: class extends self.ITextInstance {},
	М20Помидор: class extends self.ISpriteInstance {},
	М20Лук: class extends self.ISpriteInstance {},
	М20Нож: class extends self.ISpriteInstance {},
	М21Фон: class extends self.ISpriteInstance {},
	М20Анивирус2: class extends self.ISpriteInstance {},
	М21Масло: class extends self.ISpriteInstance {},
	М21Пепси: class extends self.ISpriteInstance {},
	М21Вода: class extends self.ISpriteInstance {},
	М21Соус: class extends self.ISpriteInstance {},
	М21Лимонад: class extends self.ISpriteInstance {},
	М22Фон: class extends self.ISpriteInstance {},
	М22Антивирус: class extends self.ISpriteInstance {},
	М22Сумочка: class extends self.ISpriteInstance {},
	М22Розы: class extends self.ISpriteInstance {},
	М22Кулаки: class extends self.ISpriteInstance {},
	М22Зонтик: class extends self.ISpriteInstance {},
	М22Фон2: class extends self.ISpriteInstance {},
	М22Антивирус2: class extends self.ISpriteInstance {},
	М22КДалееСумка: class extends self.ISpriteInstance {},
	М22Фон3: class extends self.ISpriteInstance {},
	М22Антивирус3: class extends self.ISpriteInstance {},
	М22КДалееКулаки: class extends self.ISpriteInstance {},
	М22Фон4: class extends self.ISpriteInstance {},
	М22Антивирус4: class extends self.ISpriteInstance {},
	М22КДалееЗонтик: class extends self.ISpriteInstance {},
	М22Фон5: class extends self.ISpriteInstance {},
	М22Антивирус5: class extends self.ISpriteInstance {},
	М22КДалееИстория: class extends self.ISpriteInstance {},
	М23Фон: class extends self.ISpriteInstance {},
	М23Антивирус: class extends self.ISpriteInstance {},
	М23КПамятник: class extends self.ISpriteInstance {},
	М23КАльбом: class extends self.ISpriteInstance {},
	М23КФотозона: class extends self.ISpriteInstance {},
	М23Фон2: class extends self.ISpriteInstance {},
	М23НинаДвижуха: class extends self.ISpriteInstance {},
	М23КПамятник2: class extends self.ISpriteInstance {},
	М23Антивирус2: class extends self.ISpriteInstance {},
	М24Фон: class extends self.ISpriteInstance {},
	М24КПриступить: class extends self.ISpriteInstance {},
	М25Фон: class extends self.ISpriteInstance {},
	М25КСтарт: class extends self.ISpriteInstance {},
	М25ПризракПазл1: class extends self.ISpriteInstance {},
	М25ПризракПазл2: class extends self.ISpriteInstance {},
	М25ПризракПазл3: class extends self.ISpriteInstance {},
	М25ПризракПазл4: class extends self.ISpriteInstance {},
	М25ПризракПазл5: class extends self.ISpriteInstance {},
	М25ПризракПазл6: class extends self.ISpriteInstance {},
	М25Пазл1: class extends self.ISpriteInstance {},
	М25Пазл2: class extends self.ISpriteInstance {},
	М25Пазл3: class extends self.ISpriteInstance {},
	М25Пазл4: class extends self.ISpriteInstance {},
	М25Пазл5: class extends self.ISpriteInstance {},
	М25Пазл6: class extends self.ISpriteInstance {},
	М26Фон: class extends self.ISpriteInstance {},
	М26ВводТекстаПожелание: class extends self.ITextInputInstance {},
	М26КОтправить: class extends self.ISpriteInstance {},
	М27Фон: class extends self.ISpriteInstance {},
	М27КДоскаПобедителей: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	Тач: class extends self.IInstance {},
	М11Проверка: class extends self.ITextInstance {},
	М13ПолеВнесения: class extends self.ISpriteInstance {},
	М13КДалее: class extends self.ISpriteInstance {},
	М15КДалееКопирка: class extends self.ISpriteInstance {},
	М19Доска: class extends self.ISpriteInstance {},
	М20Доска: class extends self.ISpriteInstance {},
	М21Миска: class extends self.ISpriteInstance {},
	М21КДалее: class extends self.ISpriteInstance {},
	М21Фон2: class extends self.ISpriteInstance {},
	М20Анивирус3: class extends self.ISpriteInstance {},
	М21КДалее2: class extends self.ISpriteInstance {},
	М20ТТекстЛук2: class extends self.ITextInstance {},
	М21Пепси2: class extends self.ISpriteInstance {},
	М17Фон4: class extends self.ISpriteInstance {},
	М17КДальше: class extends self.ISpriteInstance {},
	М17Антивирус4: class extends self.ISpriteInstance {},
	М23КДалее: class extends self.ISpriteInstance {},
	М25ТСекунды: class extends self.ITextInstance {},
	М25КДалее: class extends self.ISpriteInstance {},
	М25проверка: class extends self.ITextInstance {},
	М5Фон2: class extends self.ISpriteInstance {},
	М5ПервоеВпечатление: class extends self.ITextInstance {},
	М5Пожелание: class extends self.ITextInstance {},
	М5КЗакрыть: class extends self.ISpriteInstance {},
	М6Фон2: class extends self.ISpriteInstance {},
	М6ПервоеВпечатление: class extends self.ITextInstance {},
	М6Пожелание: class extends self.ITextInstance {},
	М6КЗакрыть: class extends self.ISpriteInstance {},
	М7Фон2: class extends self.ISpriteInstance {},
	М7ПервоеВпечатление: class extends self.ITextInstance {},
	М7Пожелание: class extends self.ITextInstance {},
	М7КЗакрыть: class extends self.ISpriteInstance {},
	М8Фон2: class extends self.ISpriteInstance {},
	М8ПервоеВпечатление: class extends self.ITextInstance {},
	М8КЗакрыть: class extends self.ISpriteInstance {},
	М8Пожелание: class extends self.ITextInstance {},
	М13Проверка: class extends self.ITextInstance {},
	М15Проверка: class extends self.ITextInstance {},
	М16Проверка: class extends self.ITextInstance {},
	М17Проверка: class extends self.ITextInstance {},
	М21Проверка: class extends self.ITextInstance {},
	М22Проверка: class extends self.ITextInstance {},
	М23Проверка: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	ВводТекста2: class extends self.ITextInputInstance {},
	М27Проверка: class extends self.ITextInstance {},
	М27ТЗагрузка: class extends self.ITextInstance {},
	М5МассивИмена: class extends self.IArrayInstance {},
	М5МассивБаллы: class extends self.IArrayInstance {},
	М5МассивВпечатления: class extends self.IArrayInstance {},
	М5МассивПожелания: class extends self.IArrayInstance {},
	JSON: class extends self.IJSONInstance {},
	М27ТЗагрузка2: class extends self.ITextInstance {},
	М26Баллы: class extends self.ITextInstance {}
}